-- Schema für MD_INGOTTYPE (Barrentypen)
-- Für H2 und Oracle kompatibel

CREATE TABLE MD_INGOTTYPE (
    ID NUMBER(19) NOT NULL,
    SERIAL NUMBER(19) DEFAULT 1,
    TABLESERIAL NUMBER(19) DEFAULT 1,
    NAME VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    LENGTH_TYPE CHAR(1),  -- S=Short, M=Medium, L=Long
    INTERNAL_ALLOWED NUMBER(1) DEFAULT 1,
    EXTERNAL_ALLOWED NUMBER(1) DEFAULT 1,
    RETRIEVAL_ALLOWED NUMBER(1) DEFAULT 1,
    AUTO_RETRIEVAL NUMBER(1) DEFAULT 0,
    MIN_LENGTH NUMBER(10),
    MAX_LENGTH NUMBER(10),
    MIN_WIDTH NUMBER(10),
    MAX_WIDTH NUMBER(10),
    MIN_THICKNESS NUMBER(10),
    MAX_THICKNESS NUMBER(10),
    MIN_WEIGHT NUMBER(10),
    MAX_WEIGHT NUMBER(10),
    PRODUCT_REGEX VARCHAR2(200),
    PRIORITY NUMBER(5) DEFAULT 0,
    CONSTRAINT PK_INGOTTYPE PRIMARY KEY (ID),
    CONSTRAINT UK_INGOTTYPE_NAME UNIQUE (NAME)
);

-- Kommentar
COMMENT ON TABLE MD_INGOTTYPE IS 'Barrentypen - Kategorien fuer Barren basierend auf Groesse und Gewicht';
COMMENT ON COLUMN MD_INGOTTYPE.LENGTH_TYPE IS 'S=Kurz, M=Mittel, L=Lang';
COMMENT ON COLUMN MD_INGOTTYPE.INTERNAL_ALLOWED IS 'Darf intern gelagert werden';
COMMENT ON COLUMN MD_INGOTTYPE.EXTERNAL_ALLOWED IS 'Darf extern gelagert werden';
COMMENT ON COLUMN MD_INGOTTYPE.RETRIEVAL_ALLOWED IS 'Darf ausgelagert werden';
COMMENT ON COLUMN MD_INGOTTYPE.AUTO_RETRIEVAL IS 'Automatische Auslagerung erlaubt';
COMMENT ON COLUMN MD_INGOTTYPE.PRODUCT_REGEX IS 'Regex fuer Produktnummer-Matching';
COMMENT ON COLUMN MD_INGOTTYPE.PRIORITY IS 'Prioritaet bei der Typ-Ermittlung (0 = hoechste)';

-- Initiale Daten basierend auf barrentypen.xls
INSERT INTO MD_INGOTTYPE (ID, NAME, DESCRIPTION, LENGTH_TYPE, INTERNAL_ALLOWED, EXTERNAL_ALLOWED, RETRIEVAL_ALLOWED, AUTO_RETRIEVAL, MIN_LENGTH, MAX_LENGTH, MIN_WEIGHT, MAX_WEIGHT, PRIORITY)
VALUES (1, 'KURZ', 'normale kurze Barren', 'S', 1, 1, 1, 0, 3500, 4300, NULL, NULL, 0);

INSERT INTO MD_INGOTTYPE (ID, NAME, DESCRIPTION, LENGTH_TYPE, INTERNAL_ALLOWED, EXTERNAL_ALLOWED, RETRIEVAL_ALLOWED, AUTO_RETRIEVAL, MIN_LENGTH, MAX_LENGTH, MIN_WEIGHT, MAX_WEIGHT, PRIORITY)
VALUES (2, 'LANG', 'normale lange Barren', 'L', 1, 1, 0, 0, 7500, 8700, NULL, NULL, 0);

INSERT INTO MD_INGOTTYPE (ID, NAME, DESCRIPTION, LENGTH_TYPE, INTERNAL_ALLOWED, EXTERNAL_ALLOWED, RETRIEVAL_ALLOWED, AUTO_RETRIEVAL, MIN_LENGTH, MAX_LENGTH, MIN_WEIGHT, MAX_WEIGHT, PRIORITY)
VALUES (3, 'MITTEL', 'mittellange Barren', 'M', 0, 1, 1, 1, 4300, 7400, NULL, 18000, 0);

COMMIT;
