-- ===================================================================
-- H2 Schema für Entwicklung (Oracle-kompatibel)
-- ===================================================================

-- AppSetting (Anwendungseinstellungen) - Stammdaten
CREATE TABLE IF NOT EXISTS MD_APPSETTING (
    SETTING_KEY     VARCHAR(50) PRIMARY KEY,
    SETTING_VALUE   VARCHAR(500),
    CATEGORY        VARCHAR(50),
    DESCRIPTION     VARCHAR(256)
);

-- Stockyard (Lagerplatz) - Stammdaten
CREATE TABLE IF NOT EXISTS MD_STOCKYARD (
    ID              BIGINT PRIMARY KEY,
    SERIAL          BIGINT NOT NULL DEFAULT 1,
    YARD_NO         VARCHAR(7) UNIQUE NOT NULL,
    X_COORDINATE    INT NOT NULL,
    Y_COORDINATE    INT NOT NULL,
    DESCRIPTION     VARCHAR(256),
    YARD_TYPE       CHAR(1) NOT NULL,      -- I=Internal, E=External, S=Saw, O=SwapOut, L=Loading
    YARD_USAGE      CHAR(1) NOT NULL,      -- S=Short, L=Long, A=Automatic
    BOTTOM_CENTER_X INT NOT NULL,          -- mm (Kran X-Position)
    BOTTOM_CENTER_Y INT NOT NULL,          -- mm (Kran Y-Position)
    BOTTOM_CENTER_Z INT DEFAULT 0,         -- mm (Kran Z-Position)
    LENGTH          INT NOT NULL,          -- mm
    WIDTH           INT NOT NULL,          -- mm
    HEIGHT          INT DEFAULT 0,         -- mm, 0 = unlimited
    MAX_INGOTS      INT NOT NULL,
    TO_STOCK_ALLOWED   BOOLEAN DEFAULT TRUE,
    FROM_STOCK_ALLOWED BOOLEAN DEFAULT TRUE,
    MOVEMENT_COEFF  INT DEFAULT 1
);

-- StockyardStatus - Bewegungsdaten
CREATE TABLE IF NOT EXISTS TD_STOCKYARDSTATUS (
    ID              BIGINT PRIMARY KEY,
    SERIAL          BIGINT NOT NULL DEFAULT 1,
    STOCKYARD_ID    BIGINT NOT NULL REFERENCES MD_STOCKYARD(ID),
    PRODUCT_ID      BIGINT,
    INGOTS_COUNT    INT DEFAULT 0,
    NEIGHBOR_ID     BIGINT,
    YARD_USAGE      CHAR(1),                       -- Überschreibt MD_STOCKYARD.YARD_USAGE
    PILE_HEIGHT     INT DEFAULT 0                  -- Aktuelle Stapelhöhe in mm
);

-- Product (Produkt/Artikel) - Stammdaten
CREATE TABLE IF NOT EXISTS MD_PRODUCT (
    ID              BIGINT PRIMARY KEY,
    SERIAL          BIGINT NOT NULL DEFAULT 1,
    PRODUCT_NO      VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPTION     VARCHAR(256),
    MAX_PER_LOCATION INT DEFAULT 8
);

-- IngotType (Barrentyp) - Stammdaten
CREATE TABLE IF NOT EXISTS MD_INGOTTYPE (
    ID              BIGINT PRIMARY KEY,
    SERIAL          BIGINT NOT NULL DEFAULT 1,
    NAME            VARCHAR(20) UNIQUE NOT NULL,
    DESCRIPTION     VARCHAR(100),
    LENGTH_TYPE     CHAR(1),          -- S=Short, M=Medium, L=Long
    INTERNAL_ALLOWED BOOLEAN DEFAULT TRUE,
    EXTERNAL_ALLOWED BOOLEAN DEFAULT TRUE,
    RETRIEVAL_ALLOWED BOOLEAN DEFAULT TRUE,
    AUTO_RETRIEVAL  BOOLEAN DEFAULT FALSE,
    MIN_LENGTH      INT,
    MAX_LENGTH      INT,
    MIN_WIDTH       INT,
    MAX_WIDTH       INT,
    MIN_THICKNESS   INT,
    MAX_THICKNESS   INT,
    MIN_WEIGHT      INT,
    MAX_WEIGHT      INT,
    PRODUCT_REGEX   VARCHAR(200),
    PRIORITY        INT DEFAULT 0
);

-- Ingot (Barren) - Bewegungsdaten
CREATE TABLE IF NOT EXISTS TD_INGOT (
    ID              BIGINT PRIMARY KEY,
    SERIAL          BIGINT NOT NULL DEFAULT 1,
    INGOT_NO        VARCHAR(20) UNIQUE NOT NULL,
    PRODUCT_ID      BIGINT REFERENCES MD_PRODUCT(ID),
    PRODUCT_SUFFIX  VARCHAR(10),
    STOCKYARD_ID    BIGINT REFERENCES MD_STOCKYARD(ID),
    PILE_POSITION   INT,
    WEIGHT          INT,           -- kg
    LENGTH          INT,           -- mm
    WIDTH           INT,           -- mm
    THICKNESS       INT,           -- mm
    HEAD_SAWN       BOOLEAN DEFAULT FALSE,
    FOOT_SAWN       BOOLEAN DEFAULT FALSE,
    SCRAP           BOOLEAN DEFAULT FALSE,
    REVISED         BOOLEAN DEFAULT FALSE,
    ROTATED         BOOLEAN DEFAULT FALSE,
    IN_STOCK_SINCE  TIMESTAMP,
    RELEASED_SINCE  TIMESTAMP,
    X_POSITION      INT,
    Y_POSITION      INT,
    Z_POSITION      INT
);

-- CraneStatus - Bewegungsdaten (nur 1 Eintrag)
CREATE TABLE IF NOT EXISTS TD_CRANESTATUS (
    ID              BIGINT PRIMARY KEY,
    SERIAL          BIGINT NOT NULL DEFAULT 1,
    X_POSITION      INT DEFAULT 0,
    Y_POSITION      INT DEFAULT 0,
    Z_POSITION      INT DEFAULT 0,
    CRANE_MODE      VARCHAR(20) DEFAULT 'AUTOMATIC',
    GRIPPER_STATE   VARCHAR(20) DEFAULT 'OPEN',
    JOB_STATE       VARCHAR(20) DEFAULT 'IDLE',
    DAEMON_STATE    VARCHAR(20) DEFAULT 'IDLE_OK',
    WORK_PHASE      VARCHAR(30) DEFAULT 'IDLE',
    FROM_STOCKYARD_ID BIGINT,
    TO_STOCKYARD_ID BIGINT,
    INCIDENT        VARCHAR(20) DEFAULT 'OK',
    INCIDENT_TEXT   VARCHAR(256),
    DOORS_OPEN      BOOLEAN DEFAULT FALSE,
    GATES_OPEN      BOOLEAN DEFAULT FALSE
);

-- PlsStatus (Säge-Status / Einlagerung) - nur 1 Eintrag
CREATE TABLE IF NOT EXISTS TD_PLSSTATUS (
    ID                  BIGINT PRIMARY KEY,
    SERIAL              BIGINT NOT NULL DEFAULT 1,
    PICKUP_MODE         VARCHAR(20) DEFAULT 'NO_PICKUP',   -- NO_PICKUP, AUTOMATIC, MANUAL
    PICKUP_NUMBER       VARCHAR(20),                       -- Einlagerungs-Nummer
    PICKUP_ORDER_ID     BIGINT,                            -- Referenz auf Einlagerungsauftrag
    PICKUP_IN_PROGRESS  BOOLEAN DEFAULT FALSE,
    ROTATE              BOOLEAN DEFAULT FALSE,
    RECEIVED_TIME       TIMESTAMP,
    POSITION_X          INT,
    POSITION_Y          INT,
    POSITION_Z          INT,
    COMPUTED_X          INT,
    COMPUTED_Y          INT,
    COMPUTED_Z          INT,
    ERROR_TYPE          VARCHAR(50),
    ERROR_MESSAGE       VARCHAR(500),
    RETURN_CONFIRMED    BOOLEAN DEFAULT FALSE,
    RECYCLE_CONFIRMED   BOOLEAN DEFAULT FALSE,
    SAWN_CONFIRMED      BOOLEAN DEFAULT FALSE
);

-- TransportOrder (Transportauftrag) - Bewegungsdaten
CREATE TABLE IF NOT EXISTS TD_TRANSPORTORDER (
    ID                  BIGINT PRIMARY KEY,
    SERIAL              BIGINT NOT NULL DEFAULT 1,
    TABLESERIAL         BIGINT NOT NULL DEFAULT 1,
    TRANSPORT_NO        VARCHAR(20) UNIQUE NOT NULL,
    NORMTEXT            VARCHAR(256),
    CALLOFF_ID          BIGINT,
    INGOT_ID            BIGINT REFERENCES TD_INGOT(ID),
    FROM_YARD_ID        BIGINT REFERENCES MD_STOCKYARD(ID),
    FROM_PILE_POSITION  INT,
    TO_YARD_ID          BIGINT REFERENCES MD_STOCKYARD(ID),
    TO_PILE_POSITION    INT,
    PRINTED             TIMESTAMP NOT NULL DEFAULT TIMESTAMP '1970-01-01 00:00:00',
    DELIVERED           TIMESTAMP NOT NULL DEFAULT TIMESTAMP '1970-01-01 00:00:00',
    -- Status-Felder für automatische Verarbeitung
    STATUS              CHAR(1) DEFAULT 'P',           -- P=Pending, I=InProgress, U=PickedUp, C=Completed, F=Failed, X=Cancelled, H=Paused
    PRIORITY            INT DEFAULT 0,
    STARTED_AT          TIMESTAMP,
    COMPLETED_AT        TIMESTAMP,
    ERROR_MESSAGE       VARCHAR(2000),                 -- Fehlermeldung (größer für lange Stack-Traces)
    RETRY_COUNT         INT DEFAULT 0
);

-- Indizes
CREATE INDEX IF NOT EXISTS IDX_STOCKYARD_COORDS ON MD_STOCKYARD(X_COORDINATE, Y_COORDINATE);
CREATE INDEX IF NOT EXISTS IDX_STOCKYARD_TYPE ON MD_STOCKYARD(YARD_TYPE);
CREATE INDEX IF NOT EXISTS IDX_STATUS_STOCKYARD ON TD_STOCKYARDSTATUS(STOCKYARD_ID);
CREATE INDEX IF NOT EXISTS IDX_INGOT_STOCKYARD ON TD_INGOT(STOCKYARD_ID);
CREATE INDEX IF NOT EXISTS IDX_TRANSPORTORDER_STATUS ON TD_TRANSPORTORDER(STATUS);
CREATE INDEX IF NOT EXISTS IDX_TRANSPORTORDER_INGOT ON TD_TRANSPORTORDER(INGOT_ID);
