-- Test-Abruf Produkt
SELECT 'Test-Abruf:' as INFO, CALLOFF_NO, PRODUCT_ID, SAP_PRODUCT_NO FROM TD_CALLOFF WHERE CALLOFF_NO LIKE '99%' OR COMPLETED = 0;

-- Barren im Lager mit Produkten
SELECT 'Barren im Lager:' as INFO, COUNT(*) as ANZAHL, PRODUCT_ID FROM TD_INGOT WHERE STOCKYARD_ID IS NOT NULL GROUP BY PRODUCT_ID;

-- Alle verfügbaren Produkte
SELECT 'Produkte:' as INFO, ID, PRODUCT_NO FROM MD_PRODUCT WHERE ROWNUM <= 10;
