-- ===================================================================
-- Test-Abrufe fuer Oracle einfuegen
-- Ausfuehren mit: sqlplus plsbl/hydroplsbl@ORCLCDB @insert_calloffs.sql
-- ===================================================================

-- Zuerst alte Test-Abrufe loeschen (falls vorhanden)
DELETE FROM TD_CALLOFF WHERE CALLOFF_NUMBER LIKE 'ABR-2026-%';

-- Abruf 1: Genehmigt, Produkt 1, 5 Barren (fuer Kran-Beladung)
INSERT INTO TD_CALLOFF (ID, SERIAL, TABLESERIAL, CALLOFF_NUMBER, ORDER_NUMBER, ORDER_POSITION,
    CUSTOMER_NUMBER, CUSTOMER_NAME, CUSTOMER_ADDRESS, DESTINATION,
    SAP_PRODUCT_NUMBER, PRODUCT_ID, AMOUNT_REQUESTED, AMOUNT_DELIVERED,
    DELIVERY_DATE, APPROVED, COMPLETED, RECEIVED, NOTES) VALUES
((SELECT NVL(MAX(ID),0)+1 FROM TD_CALLOFF), 1, 1, 'ABR-2026-0001', 'SAP-4711', '010',
    'K-100', 'Mustermann GmbH', 'Musterstrasse 1, 12345 Musterstadt', 'Werk Sued',
    'PROD-001', 1, 5, 0,
    SYSDATE, 1, 0, SYSTIMESTAMP, 'Test-Abruf fuer Kran-Beladung');

-- Abruf 2: Genehmigt, Produkt 2, 3 Barren (Eilauftrag)
INSERT INTO TD_CALLOFF (ID, SERIAL, TABLESERIAL, CALLOFF_NUMBER, ORDER_NUMBER, ORDER_POSITION,
    CUSTOMER_NUMBER, CUSTOMER_NAME, CUSTOMER_ADDRESS, DESTINATION,
    SAP_PRODUCT_NUMBER, PRODUCT_ID, AMOUNT_REQUESTED, AMOUNT_DELIVERED,
    DELIVERY_DATE, APPROVED, COMPLETED, RECEIVED, NOTES) VALUES
((SELECT NVL(MAX(ID),0)+1 FROM TD_CALLOFF), 1, 2, 'ABR-2026-0002', 'SAP-4712', '020',
    'K-200', 'Beispiel AG', 'Beispielweg 42, 54321 Beispielburg', 'Lager Nord',
    'PROD-002', 2, 3, 0,
    SYSDATE + 1, 1, 0, SYSTIMESTAMP, 'Eilauftrag - dringend');

-- Abruf 3: Nicht genehmigt (muss erst freigegeben werden)
INSERT INTO TD_CALLOFF (ID, SERIAL, TABLESERIAL, CALLOFF_NUMBER, ORDER_NUMBER, ORDER_POSITION,
    CUSTOMER_NUMBER, CUSTOMER_NAME, CUSTOMER_ADDRESS, DESTINATION,
    SAP_PRODUCT_NUMBER, PRODUCT_ID, AMOUNT_REQUESTED, AMOUNT_DELIVERED,
    DELIVERY_DATE, APPROVED, COMPLETED, RECEIVED, NOTES) VALUES
((SELECT NVL(MAX(ID),0)+1 FROM TD_CALLOFF), 1, 3, 'ABR-2026-0003', 'SAP-4713', '010',
    'K-300', 'Test Kunde', 'Testgasse 99, 99999 Testheim', 'Export',
    'PROD-001', 1, 10, 0,
    SYSDATE + 7, 0, 0, SYSTIMESTAMP, 'Wartet auf Freigabe');

-- Abruf 4: Teilweise geliefert, Produkt 1
INSERT INTO TD_CALLOFF (ID, SERIAL, TABLESERIAL, CALLOFF_NUMBER, ORDER_NUMBER, ORDER_POSITION,
    CUSTOMER_NUMBER, CUSTOMER_NAME, CUSTOMER_ADDRESS, DESTINATION,
    SAP_PRODUCT_NUMBER, PRODUCT_ID, AMOUNT_REQUESTED, AMOUNT_DELIVERED,
    DELIVERY_DATE, APPROVED, COMPLETED, RECEIVED, NOTES) VALUES
((SELECT NVL(MAX(ID),0)+1 FROM TD_CALLOFF), 1, 4, 'ABR-2026-0004', 'SAP-4714', '030',
    'K-100', 'Mustermann GmbH', 'Musterstrasse 1, 12345 Musterstadt', 'Werk Sued',
    'PROD-001', 1, 8, 3,
    SYSDATE, 1, 0, SYSTIMESTAMP - INTERVAL '2' DAY, 'Teillieferung - Rest offen');

-- Abruf 5: Abgeschlossen (zur Ansicht in Historie)
INSERT INTO TD_CALLOFF (ID, SERIAL, TABLESERIAL, CALLOFF_NUMBER, ORDER_NUMBER, ORDER_POSITION,
    CUSTOMER_NUMBER, CUSTOMER_NAME, CUSTOMER_ADDRESS, DESTINATION,
    SAP_PRODUCT_NUMBER, PRODUCT_ID, AMOUNT_REQUESTED, AMOUNT_DELIVERED,
    DELIVERY_DATE, APPROVED, COMPLETED, RECEIVED, NOTES) VALUES
((SELECT NVL(MAX(ID),0)+1 FROM TD_CALLOFF), 1, 5, 'ABR-2026-0005', 'SAP-4710', '010',
    'K-400', 'Fertig KG', 'Fertigstrasse 5, 55555 Fertigdorf', 'Inland',
    'PROD-002', 2, 4, 4,
    SYSDATE - 3, 1, 1, SYSTIMESTAMP - INTERVAL '5' DAY, 'Vollstaendig geliefert');

COMMIT;

-- Ergebnis anzeigen
SELECT CALLOFF_NUMBER, CUSTOMER_NAME, AMOUNT_REQUESTED AS ANGEF, AMOUNT_DELIVERED AS GELIEF,
       CASE WHEN APPROVED = 1 THEN 'Ja' ELSE 'Nein' END AS GENEHM,
       CASE WHEN COMPLETED = 1 THEN 'Ja' ELSE 'Nein' END AS FERTIG
FROM TD_CALLOFF
WHERE CALLOFF_NUMBER LIKE 'ABR-2026-%'
ORDER BY CALLOFF_NUMBER;

PROMPT;
PROMPT === 5 Test-Abrufe eingefuegt ===;
